#!/usr/bin/env python3
"""Unified configuration and launch commands; requires Python 3.11+ only."""

from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import re
import secrets
import subprocess
import sys
import tempfile
import tomllib
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
PROJECTS = {
    "control-plane": "apps/control-plane",
    "ai-worker": "apps/ai-worker",
    "api-ui-worker": "apps/api-ui-worker",
    "zentao": "apps/connector-zentao",
    "studio": "apps/studio",
}


def merge(base, override):
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def toml_text(data):
    lines = ["# Generated by scripts/manage.py; edit config/platform.toml instead."]

    def scalar(value):
        if isinstance(value, bool):
            return str(value).lower()
        if isinstance(value, str):
            return json.dumps(value, ensure_ascii=False)
        if isinstance(value, (int, float)):
            return repr(value)
        if isinstance(value, list):
            return "[" + ", ".join(scalar(item) for item in value) + "]"
        raise ValueError(f"Unsupported TOML value type: {type(value).__name__}")

    def emit(table, path):
        if path:
            lines.extend(["", "[" + ".".join(json.dumps(k) for k in path) + "]"])
        for key, value in table.items():
            if not isinstance(value, dict):
                lines.append(f"{json.dumps(key)} = {scalar(value)}")
        for key, value in table.items():
            if isinstance(value, dict):
                emit(value, path + [key])

    emit(data, [])
    return "\n".join(lines) + "\n"


def read(path):
    with path.open("rb") as stream:
        return tomllib.load(stream)


def write(path, content, *, container=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    # Atomic replacement prevents readers seeing a partly generated file.
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=path.name + ".",
        suffix=".tmp",
        delete=False,
    ) as stream:
        temp = Path(stream.name)
        stream.write(content)
    try:
        temp.chmod(0o644 if container else 0o600)
        temp.replace(path)
    finally:
        temp.unlink(missing_ok=True)


def init(root=ROOT):
    path = root / "config/platform.toml"
    if path.exists():
        print("Existing config/platform.toml preserved.")
        return
    data = read(root / "config/platform.example.toml")
    for section in data.values():
        if isinstance(section, dict):
            for key, value in section.items():
                if value == "GENERATE":
                    section[key] = secrets.token_hex(32)
    write(path, toml_text(data))
    print("Created config/platform.toml with fresh local credentials.")


def validate(data):
    shared, db = data["shared"], data["database"]
    for key in ("worker_token", "jwt_key", "integration_key"):
        if not shared[key] or shared[key] == "GENERATE":
            raise ValueError(f"Set shared.{key}, or run init first")
    for key in ("password", "root_password"):
        if not db[key] or db[key] == "GENERATE":
            raise ValueError(f"Set database.{key}, or run init first")
    for key in ("name", "user"):
        if not re.fullmatch(r"[A-Za-z0-9_]+", db[key]):
            raise ValueError(
                f"database.{key} must contain letters, digits or underscores"
            )
    if db["user"] == "root":
        raise ValueError("database.user must be a non-root application user")
    for key in ("public_host", "local_host", "bind_host"):
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", shared[key]):
            raise ValueError(
                f"shared.{key} must be an IPv4 address or hostname without a port"
            )
    ports = [
        shared[k]
        for k in (
            "studio_port",
            "control_plane_port",
            "zentao_port",
            "artifacts_port",
            "mysql_port",
        )
    ]
    if any(type(p) is not int or not 1 <= p <= 65535 for p in ports) or len(
        set(ports)
    ) != len(ports):
        raise ValueError("Service ports must be distinct integers between 1 and 65535")


def configurations(data, mode, root=ROOT):
    validate(data)
    s, db = data["shared"], data["database"]
    docker = mode == "docker"
    host = s["local_host"]
    cp_url = (
        "http://control-plane:9000"
        if docker
        else f"http://{host}:{s['control_plane_port']}"
    )
    z_url = "http://zentao:8010" if docker else f"http://{host}:{s['zentao_port']}"
    db_host = "mysql" if docker else host
    db_port = 3306 if docker else s["mysql_port"]
    dsn = f"mysql+asyncmy://{quote(db['user'], safe='')}:{quote(db['password'], safe='')}@{db_host}:{db_port}/{db['name']}?charset=utf8mb4"
    specs = {
        "control-plane": ("config/local.example.toml", "control_plane"),
        "ai-worker": ("config/worker.example.toml", "ai_worker"),
        "api-ui-worker": ("config.example.toml", "api_ui_worker"),
        "zentao": ("config/zentao.example.toml", "zentao"),
    }
    result = {
        name: merge(read(root / PROJECTS[name] / file), data.get(section, {}))
        for name, (file, section) in specs.items()
    }
    result["control-plane"] = merge(
        result["control-plane"],
        {
            "env": "production" if docker else "local",
            "http": {
                "host": "0.0.0.0" if docker else host,
                "port": 9000 if docker else s["control_plane_port"],
            },
            "security": {
                "jwt": {"key": s["jwt_key"]},
                "integration": {"key": s["integration_key"]},
                "worker": {"key": s["worker_token"]},
            },
            "data": {"db": {"user": {"dsn": dsn}}},
            "storage": {
                "uploads_dir": "/app/storage/ai-generate-task-sources"
                if docker
                else "storage/ai-generate-task-sources"
            },
            "integrations": {"zentao_service": {"base_url": z_url}},
        },
    )
    result["ai-worker"] = merge(
        result["ai-worker"],
        {
            "platform": {"base_url": cp_url, "worker_token": s["worker_token"]},
            "nanobot": {"runtime_root": "/data/runtime" if docker else "runtime"},
            "logging": {"dir": "/app/logs" if docker else "logs"},
        },
    )
    result["api-ui-worker"] = merge(
        result["api-ui-worker"],
        {
            "control_plane": {"base_url": cp_url, "worker_token": s["worker_token"]},
            "ui": {
                "artifacts_dir": "/app/artifacts" if docker else "artifacts",
                "artifacts_bind_host": "0.0.0.0" if docker else s["bind_host"],
                "artifacts_port": 9010 if docker else s["artifacts_port"],
                "artifacts_base_url": f"http://{s['public_host']}:{s['artifacts_port']}",
            },
        },
    )
    result["zentao"] = merge(
        result["zentao"],
        {
            "service": {
                "host": "0.0.0.0" if docker else host,
                "port": 8010 if docker else s["zentao_port"],
                "app_env": "production" if docker else "local",
            }
        },
    )
    return result


def env_text(values):
    # Compose and Vite dotenv both preserve literal dollars in single quotes.
    return "".join(
        key + "='" + str(value).replace("'", "\\'") + "'\n"
        for key, value in values.items()
    )


def configure(mode, root=ROOT):
    data = read(root / "config/platform.toml")
    configs = configurations(data, mode, root)
    runtime = root / ".runtime"
    runtime.mkdir(exist_ok=True)
    runtime.chmod(0o700)
    local_files = {
        "control-plane": "config/local.toml",
        "ai-worker": "config/worker.toml",
        "api-ui-worker": "config.toml",
        "zentao": "config/zentao.toml",
    }
    for name, config in configs.items():
        path = (
            runtime / "docker" / f"{name}.toml"
            if mode == "docker"
            else root / PROJECTS[name] / local_files[name]
        )
        write(path, toml_text(config), container=mode == "docker")
    s, db = data["shared"], data["database"]
    if mode == "docker":
        env = {
            k.upper(): s[k]
            for k in (
                "bind_host",
                "studio_port",
                "control_plane_port",
                "zentao_port",
                "artifacts_port",
                "mysql_port",
            )
        }
        env.update(
            MYSQL_DATABASE=db["name"],
            MYSQL_USER=db["user"],
            MYSQL_PASSWORD=db["password"],
            MYSQL_ROOT_PASSWORD=db["root_password"],
        )
        write(runtime / "compose.env", env_text(env))
    else:
        write(
            root / PROJECTS["studio"] / ".env.local",
            env_text(
                {
                    "VITE_API_PROXY_TARGET": f"http://{s['local_host']}:{s['control_plane_port']}"
                }
            ),
        )
    print(f"Generated {mode} configuration.")


def compose_command(root=ROOT):
    return [
        "docker",
        "compose",
        "--project-directory",
        str(root),
        "--env-file",
        str(root / ".runtime/compose.env"),
        "-f",
        str(root / "compose.yaml"),
    ]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="action", required=True)
    sub.add_parser(
        "init", help="Create unified local config without replacing an existing one"
    )
    config = sub.add_parser("configure", help="Generate service configuration")
    config.add_argument("--mode", choices=["local", "docker"], default="docker")
    run = sub.add_parser(
        "run", help="Run one service locally; install its dependencies first"
    )
    run.add_argument("service", choices=PROJECTS)
    sub.add_parser(
        "migrate", help="Apply database migrations using local configuration"
    )
    compose = sub.add_parser(
        "compose",
        help="Generate Docker config and forward remaining args to Docker Compose",
    )
    compose.add_argument("args", nargs=argparse.REMAINDER)
    argv = sys.argv[1:]
    args = parser.parse_args(["compose"] if argv[:1] == ["compose"] else argv)
    if args.action == "compose":
        args.args = argv[1:]
    if args.action == "init":
        init()
        return
    if args.action == "configure":
        configure(args.mode)
        return
    if args.action == "compose":
        configure("docker")
        raise SystemExit(subprocess.call(compose_command() + args.args, cwd=ROOT))
    configure("local")
    name = "control-plane" if args.action == "migrate" else args.service
    commands = {
        "control-plane": ["uv", "run", "--locked", "mtx-control-plane"],
        "ai-worker": ["uv", "run", "--locked", "mtx-ai-worker"],
        "api-ui-worker": ["uv", "run", "--locked", "mtx-api-ui-worker"],
        "zentao": ["uv", "run", "--locked", "python", "main.py"],
        "studio": ["npm", "run", "dev"],
    }
    command = (
        ["uv", "run", "--locked", "alembic", "upgrade", "head"]
        if args.action == "migrate"
        else commands[name]
    )
    env = os.environ.copy()
    if name == "control-plane":
        env["APP_CONF"] = str(ROOT / PROJECTS[name] / "config/local.toml")
    raise SystemExit(subprocess.call(command, cwd=ROOT / PROJECTS[name], env=env))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, FileNotFoundError, tomllib.TOMLDecodeError) as exc:
        print(f"Configuration error: {exc}", file=sys.stderr)
        raise SystemExit(2) from None
