"""Initialize the complete control-plane schema in an empty database.

This frozen baseline replaces the development migration chain. Existing
pre-baseline databases are intentionally unsupported; no data is backfilled.

Revision ID: 20260915_0001
Revises: None
"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision = "20260915_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_generate_task_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_user_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("checkpoint_enabled", sa.Boolean(), nullable=False),
        sa.Column("current_stage", sa.String(length=40), nullable=False),
        sa.Column("snapshot_json", mysql.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generate_task_runs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_ai_generate_task_runs_run_id")),
    )
    op.create_index(
        op.f("ix_ai_generate_task_runs_task_id"), "ai_generate_task_runs", ["task_id"], unique=False
    )
    op.create_table(
        "ai_generate_task_source_archives",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generate_task_source_archives")),
        sa.UniqueConstraint(
            "archive_id", name=op.f("uq_ai_generate_task_source_archives_archive_id")
        ),
        sa.UniqueConstraint("task_id", name=op.f("uq_ai_generate_task_source_archives_task_id")),
    )
    op.create_table(
        "ai_generate_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("sprint_id", sa.String(length=64), nullable=False),
        sa.Column("requirement_id", sa.String(length=64), nullable=False),
        sa.Column("creator_user_id", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_content", mysql.LONGTEXT(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generate_tasks")),
        sa.UniqueConstraint("task_id", name=op.f("uq_ai_generate_tasks_task_id")),
    )
    op.create_index(
        "ix_ai_generate_tasks_creator_user_id_deleted_at",
        "ai_generate_tasks",
        ["creator_user_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_generate_tasks_project_id_deleted_at",
        "ai_generate_tasks",
        ["project_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_generate_tasks_requirement_id_deleted_at",
        "ai_generate_tasks",
        ["requirement_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_generate_tasks_sprint_id_deleted_at",
        "ai_generate_tasks",
        ["sprint_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_generate_tasks_task_type"), "ai_generate_tasks", ["task_type"], unique=False
    )
    op.create_table(
        "api_assert_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("assert_rule_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("assert_source", sa.String(length=30), nullable=False),
        sa.Column("target_expr", sa.String(length=512), nullable=False),
        sa.Column("comparator", sa.String(length=30), nullable=False),
        sa.Column("expected_value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_assert_rules")),
        sa.UniqueConstraint("assert_rule_id", name=op.f("uq_api_assert_rules_assert_rule_id")),
        sa.UniqueConstraint("case_id", "name", name="uk_case_assert_name"),
    )
    op.create_index(
        "idx_case_assert_order", "api_assert_rules", ["case_id", "order_no"], unique=False
    )
    op.create_index(
        "ix_api_assert_rules_case_id_deleted_at",
        "api_assert_rules",
        ["case_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "api_collection_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("collection_run_id", sa.String(length=64), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("environment_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_user_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("runtime_vars_json", mysql.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_collection_runs")),
        sa.UniqueConstraint(
            "collection_run_id", name=op.f("uq_api_collection_runs_collection_run_id")
        ),
    )
    op.create_index(
        op.f("ix_api_collection_runs_collection_id"),
        "api_collection_runs",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_collection_runs_environment_id"),
        "api_collection_runs",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_collection_runs_status"), "api_collection_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_api_collection_runs_trigger_user_id"),
        "api_collection_runs",
        ["trigger_user_id"],
        unique=False,
    )
    op.create_table(
        "api_environment_vars",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("env_var_id", sa.String(length=64), nullable=False),
        sa.Column("environment_id", sa.String(length=64), nullable=False),
        sa.Column("var_key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_environment_vars")),
        sa.UniqueConstraint("env_var_id", name=op.f("uq_api_environment_vars_env_var_id")),
        sa.UniqueConstraint("environment_id", "var_key", name="uk_api_env_var_key"),
    )
    op.create_index(
        op.f("ix_api_environment_vars_environment_id"),
        "api_environment_vars",
        ["environment_id"],
        unique=False,
    )
    op.create_table(
        "api_environments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("environment_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_environments")),
        sa.UniqueConstraint("environment_id", name=op.f("uq_api_environments_environment_id")),
        sa.UniqueConstraint("project_id", "name", name="uk_api_environment_project_name"),
    )
    op.create_index(
        "ix_api_environments_project_id_deleted_at",
        "api_environments",
        ["project_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "api_extract_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("extract_rule_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_expr", sa.String(length=512), nullable=False),
        sa.Column("var_key", sa.String(length=120), nullable=False),
        sa.Column("default_value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_extract_rules")),
        sa.UniqueConstraint("case_id", "var_key", name="uk_case_extract_var"),
        sa.UniqueConstraint("extract_rule_id", name=op.f("uq_api_extract_rules_extract_rule_id")),
    )
    op.create_index(
        "idx_case_extract_order", "api_extract_rules", ["case_id", "order_no"], unique=False
    )
    op.create_index(
        "ix_api_extract_rules_case_id_deleted_at",
        "api_extract_rules",
        ["case_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "function_test_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("suite_id", sa.String(length=64), nullable=False),
        sa.Column("module", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("case_type", sa.String(length=30), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_json", mysql.JSON(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_function_test_cases")),
        sa.UniqueConstraint("case_id", name=op.f("uq_function_test_cases_case_id")),
        sa.UniqueConstraint("suite_id", "title", name="uk_function_case_suite_title"),
    )
    op.create_index(
        "idx_function_case_suite_order",
        "function_test_cases",
        ["suite_id", "order_no"],
        unique=False,
    )
    op.create_index(
        "ix_function_test_cases_suite_id_deleted_at",
        "function_test_cases",
        ["suite_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "integration_connections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("connection_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("auth_type", sa.String(length=50), nullable=False),
        sa.Column("account", sa.String(length=120), nullable=False),
        sa.Column("secret_json", mysql.JSON(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_auth_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_auth_error", sa.Text(), nullable=False),
        sa.Column("extra_json", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_connections")),
        sa.UniqueConstraint("connection_id", name=op.f("uq_integration_connections_connection_id")),
        sa.UniqueConstraint("user_id", "provider", "name", name="uk_connection_user_provider_name"),
    )
    op.create_index(
        "ix_integration_connections_project_id_deleted_at",
        "integration_connections",
        ["project_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_provider"),
        "integration_connections",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_status"),
        "integration_connections",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_integration_connections_user_id_deleted_at",
        "integration_connections",
        ["user_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "project_skill_spaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_space_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=128), nullable=False),
        sa.Column("download_url", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_skill_spaces")),
        sa.UniqueConstraint("project_id", "filename", name="uk_project_skill_filename"),
        sa.UniqueConstraint("skill_space_id", name=op.f("uq_project_skill_spaces_skill_space_id")),
    )
    op.create_index(
        "ix_project_skill_spaces_project_id_deleted_at",
        "project_skill_spaces",
        ["project_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("project_id", name=op.f("uq_projects_project_id")),
        sa.UniqueConstraint("user_id", "name", name="uk_project_user_name"),
    )
    op.create_index(
        "ix_projects_user_id_deleted_at", "projects", ["user_id", "deleted_at"], unique=False
    )
    op.create_table(
        "resource_bindings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("binding_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("connection_id", sa.String(length=64), nullable=False),
        sa.Column("local_resource_type", sa.String(length=30), nullable=False),
        sa.Column("local_resource_id", sa.String(length=64), nullable=False),
        sa.Column("remote_resource_type", sa.String(length=30), nullable=False),
        sa.Column("remote_resource_id", sa.String(length=120), nullable=False),
        sa.Column("remote_parent_id", sa.String(length=120), nullable=False),
        sa.Column("remote_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_json", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_bindings")),
        sa.UniqueConstraint("binding_id", name=op.f("uq_resource_bindings_binding_id")),
        sa.UniqueConstraint(
            "provider",
            "local_resource_type",
            "local_resource_id",
            "remote_resource_type",
            "remote_resource_id",
            name="uq_binding_resource",
        ),
    )
    op.create_index(
        "idx_binding_connection", "resource_bindings", ["connection_id", "status"], unique=False
    )
    op.create_index(
        "idx_binding_local",
        "resource_bindings",
        ["user_id", "local_resource_type", "local_resource_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_binding_remote",
        "resource_bindings",
        ["provider", "remote_resource_type", "remote_resource_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_bindings_user_id"), "resource_bindings", ["user_id"], unique=False
    )
    op.create_table(
        "sprint_daily_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("metric_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("sprint_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("function_case_total", sa.Integer(), nullable=False),
        sa.Column("function_case_executed", sa.Integer(), nullable=False),
        sa.Column("function_case_pending", sa.Integer(), nullable=False),
        sa.Column("function_case_success", sa.Integer(), nullable=False),
        sa.Column("function_case_failed", sa.Integer(), nullable=False),
        sa.Column("api_case_total", sa.Integer(), nullable=False),
        sa.Column("api_case_executed", sa.Integer(), nullable=False),
        sa.Column("api_case_pending", sa.Integer(), nullable=False),
        sa.Column("api_case_success", sa.Integer(), nullable=False),
        sa.Column("api_case_failed", sa.Integer(), nullable=False),
        sa.Column("ui_case_total", sa.Integer(), nullable=False),
        sa.Column("ui_case_executed", sa.Integer(), nullable=False),
        sa.Column("ui_case_pending", sa.Integer(), nullable=False),
        sa.Column("ui_case_success", sa.Integer(), nullable=False),
        sa.Column("ui_case_failed", sa.Integer(), nullable=False),
        sa.Column("bug_total", sa.Integer(), nullable=False),
        sa.Column("bug_resolved", sa.Integer(), nullable=False),
        sa.Column("bug_closed", sa.Integer(), nullable=False),
        sa.Column("bug_unresolved", sa.Integer(), nullable=False),
        sa.Column("bug_fatal", sa.Integer(), nullable=False),
        sa.Column("bug_serious", sa.Integer(), nullable=False),
        sa.Column("bug_normal", sa.Integer(), nullable=False),
        sa.Column("bug_suggestion", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sprint_daily_metrics")),
        sa.UniqueConstraint("metric_id", name=op.f("uq_sprint_daily_metrics_metric_id")),
        sa.UniqueConstraint("sprint_id", "snapshot_date", name="uk_sprint_date"),
    )
    op.create_index(
        op.f("ix_sprint_daily_metrics_project_id"),
        "sprint_daily_metrics",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sprint_daily_metrics_snapshot_date"),
        "sprint_daily_metrics",
        ["snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sprint_daily_metrics_sprint_id"),
        "sprint_daily_metrics",
        ["sprint_id"],
        unique=False,
    )
    op.create_table(
        "sprints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sprint_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "end_time > start_time", name=op.f("ck_sprints_sprint_end_time_after_start_time")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sprints")),
        sa.UniqueConstraint("project_id", "name", name="uk_sprint_project_name"),
        sa.UniqueConstraint("sprint_id", name=op.f("uq_sprints_sprint_id")),
    )
    op.create_index(
        "ix_sprints_project_id_deleted_at", "sprints", ["project_id", "deleted_at"], unique=False
    )
    op.create_table(
        "ui_test_case_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("suite_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_user_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("snapshot_json", mysql.JSON(), nullable=True),
        sa.Column("step_results_json", mysql.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ui_test_case_runs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_ui_test_case_runs_run_id")),
    )
    op.create_index(
        op.f("ix_ui_test_case_runs_case_id"), "ui_test_case_runs", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_ui_test_case_runs_status"), "ui_test_case_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ui_test_case_runs_suite_id"), "ui_test_case_runs", ["suite_id"], unique=False
    )
    op.create_index(
        op.f("ix_ui_test_case_runs_trigger_user_id"),
        "ui_test_case_runs",
        ["trigger_user_id"],
        unique=False,
    )
    op.create_table(
        "ui_test_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("suite_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("steps_json", mysql.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ui_test_cases")),
        sa.UniqueConstraint("case_id", name=op.f("uq_ui_test_cases_case_id")),
        sa.UniqueConstraint("suite_id", "name", name="uk_ui_case_suite_name"),
    )
    op.create_index(
        "idx_ui_test_cases_suite_order", "ui_test_cases", ["suite_id", "order_no"], unique=False
    )
    op.create_index(
        "ix_ui_test_cases_suite_id_deleted_at",
        "ui_test_cases",
        ["suite_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "ui_test_suite_run_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("suite_run_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("continue_on_failure", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("snapshot_json", mysql.JSON(), nullable=True),
        sa.Column("step_results_json", mysql.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ui_test_suite_run_items")),
        sa.UniqueConstraint("item_id", name=op.f("uq_ui_test_suite_run_items_item_id")),
    )
    op.create_index(
        "idx_ui_suite_run_item_order",
        "ui_test_suite_run_items",
        ["suite_run_id", "order_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_test_suite_run_items_case_id"),
        "ui_test_suite_run_items",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_test_suite_run_items_status"),
        "ui_test_suite_run_items",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ui_test_suite_run_items_suite_run_id"),
        "ui_test_suite_run_items",
        ["suite_run_id"],
        unique=False,
    )
    op.create_table(
        "ui_test_suite_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("suite_run_id", sa.String(length=64), nullable=False),
        sa.Column("suite_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_user_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", mysql.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ui_test_suite_runs")),
        sa.UniqueConstraint("suite_run_id", name=op.f("uq_ui_test_suite_runs_suite_run_id")),
    )
    op.create_index(
        op.f("ix_ui_test_suite_runs_status"), "ui_test_suite_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ui_test_suite_runs_suite_id"), "ui_test_suite_runs", ["suite_id"], unique=False
    )
    op.create_index(
        op.f("ix_ui_test_suite_runs_trigger_user_id"),
        "ui_test_suite_runs",
        ["trigger_user_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("nickname", name=op.f("uq_users_nickname")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_user_id")),
    )
    op.create_table(
        "worker_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("domain", sa.String(length=10), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("worker_id", sa.String(length=120), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_tasks")),
        sa.UniqueConstraint("domain", "task_id", name="uk_worker_domain_task"),
    )
    op.create_index(
        "idx_worker_domain_status_created",
        "worker_tasks",
        ["domain", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_worker_tasks_lease_expires_at"), "worker_tasks", ["lease_expires_at"], unique=False
    )
    op.create_index(op.f("ix_worker_tasks_run_id"), "worker_tasks", ["run_id"], unique=False)
    op.create_table(
        "ai_generate_run_stages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("stage_order", sa.Integer(), nullable=False),
        sa.Column("execution_status", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("current_artifact_attempt_id", sa.String(length=64), nullable=True),
        sa.Column("active_attempt_id", sa.String(length=64), nullable=True),
        sa.Column("reviewer_user_id", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_generate_task_runs.run_id"],
            name=op.f("fk_ai_generate_run_stages_run_id_ai_generate_task_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generate_run_stages")),
        sa.UniqueConstraint("run_id", "stage", name=op.f("uq_ai_generate_run_stages_run_id")),
    )
    op.create_table(
        "requirements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("requirement_id", sa.String(length=64), nullable=False),
        sa.Column("sprint_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("document_type", sa.String(length=20), nullable=False),
        sa.Column("document_content", mysql.LONGTEXT(), nullable=False),
        sa.Column("document_filename", sa.String(length=255), nullable=False),
        sa.Column("document_hash", sa.String(length=128), nullable=False),
        sa.Column("document_storage_path", sa.String(length=512), nullable=False),
        sa.Column("document_download_url", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["sprint_id"], ["sprints.sprint_id"], name="fk_requirements_sprint"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
        sa.UniqueConstraint("requirement_id", name=op.f("uq_requirements_requirement_id")),
        sa.UniqueConstraint("sprint_id", "name", name="uk_requirement_sprint_name"),
    )
    op.create_index(
        "ix_requirements_sprint_id_deleted_at",
        "requirements",
        ["sprint_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "ai_generate_stage_attempts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("stage_id", sa.String(length=64), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("worker_task_id", sa.String(length=64), nullable=True),
        sa.Column("requested_by", sa.String(length=64), nullable=True),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("revision_instruction", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "output_content", sa.Text().with_variant(mysql.LONGTEXT(), "mysql"), nullable=True
        ),
        sa.Column("output_context_json", sa.JSON(), nullable=True),
        sa.Column("output_format", sa.String(length=20), nullable=True),
        sa.Column("progress_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["ai_generate_run_stages.id"],
            name=op.f("fk_ai_generate_stage_attempts_stage_id_ai_generate_run_stages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generate_stage_attempts")),
        sa.UniqueConstraint("stage_id", "attempt_no", name="uq_ai_attempt_stage_number"),
        sa.UniqueConstraint("stage_id", "worker_task_id", name="uq_ai_attempt_stage_worker"),
    )
    op.create_index(
        op.f("ix_ai_generate_stage_attempts_worker_task_id"),
        "ai_generate_stage_attempts",
        ["worker_task_id"],
        unique=False,
    )
    op.create_table(
        "api_collections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("requirement_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.requirement_id"],
            name="fk_api_collections_requirement",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_collections")),
        sa.UniqueConstraint("collection_id", name=op.f("uq_api_collections_collection_id")),
        sa.UniqueConstraint("requirement_id", "name", name="uk_api_collection_requirement_name"),
    )
    op.create_index(
        "ix_api_collections_requirement_id_deleted_at",
        "api_collections",
        ["requirement_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "function_test_suites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("suite_id", sa.String(length=64), nullable=False),
        sa.Column("requirement_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.requirement_id"],
            name="fk_function_test_suites_requirement",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_function_test_suites")),
        sa.UniqueConstraint("requirement_id", "name", name="uk_function_suite_requirement_name"),
        sa.UniqueConstraint("suite_id", name=op.f("uq_function_test_suites_suite_id")),
    )
    op.create_index(
        "ix_function_test_suites_requirement_id_deleted_at",
        "function_test_suites",
        ["requirement_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "ui_test_suites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("suite_id", sa.String(length=64), nullable=False),
        sa.Column("requirement_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("headless", sa.Boolean(), nullable=True),
        sa.Column("slow_mo_ms", sa.Integer(), nullable=True),
        sa.Column("viewport_width", sa.Integer(), nullable=True),
        sa.Column("viewport_height", sa.Integer(), nullable=True),
        sa.Column("default_step_timeout_ms", sa.Integer(), nullable=True),
        sa.Column("screenshot_policy", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.requirement_id"],
            name="fk_ui_test_suites_requirement",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ui_test_suites")),
        sa.UniqueConstraint("requirement_id", "name", name="uk_ui_suite_requirement_name"),
        sa.UniqueConstraint("suite_id", name=op.f("uq_ui_test_suites_suite_id")),
    )
    op.create_index(
        "ix_ui_test_suites_requirement_id_deleted_at",
        "ui_test_suites",
        ["requirement_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "ai_generate_run_imports",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_attempt_id", sa.String(length=64), nullable=True),
        sa.Column("imported_by", sa.String(length=64), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("imported_targets_json", sa.JSON(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_attempt_id"],
            ["ai_generate_stage_attempts.id"],
            name=op.f("fk_ai_generate_run_imports_artifact_attempt_id_ai_generate_stage_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_generate_task_runs.run_id"],
            name=op.f("fk_ai_generate_run_imports_run_id_ai_generate_task_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generate_run_imports")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_ai_generate_run_imports_idempotency_key")
        ),
        sa.UniqueConstraint("run_id", name=op.f("uq_ai_generate_run_imports_run_id")),
    )
    op.create_table(
        "api_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("url_template", sa.String(length=1024), nullable=False),
        sa.Column("headers_json", mysql.JSON(), nullable=True),
        sa.Column("query_json", mysql.JSON(), nullable=True),
        sa.Column("body_type", sa.String(length=20), nullable=False),
        sa.Column("body_json", mysql.JSON(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("continue_on_failure", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["api_collections.collection_id"], name="fk_api_cases_collection"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_cases")),
        sa.UniqueConstraint("case_id", name=op.f("uq_api_cases_case_id")),
    )
    op.create_index(
        "idx_api_case_collection_order", "api_cases", ["collection_id", "order_no"], unique=False
    )
    op.create_index(
        "ix_api_cases_collection_id_deleted_at",
        "api_cases",
        ["collection_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "api_case_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("collection_run_id", sa.String(length=64), nullable=True),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("environment_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_user_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("request_snapshot_json", mysql.JSON(), nullable=True),
        sa.Column("response_snapshot_json", mysql.JSON(), nullable=True),
        sa.Column("runtime_vars_json", mysql.JSON(), nullable=True),
        sa.Column("extract_results_json", mysql.JSON(), nullable=True),
        sa.Column("assert_results_json", mysql.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["api_cases.case_id"], name="fk_api_case_runs_case"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_case_runs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_api_case_runs_run_id")),
    )
    op.create_index(op.f("ix_api_case_runs_case_id"), "api_case_runs", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_api_case_runs_collection_id"), "api_case_runs", ["collection_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_case_runs_collection_run_id"),
        "api_case_runs",
        ["collection_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_case_runs_environment_id"), "api_case_runs", ["environment_id"], unique=False
    )
    op.create_index(op.f("ix_api_case_runs_status"), "api_case_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_api_case_runs_trigger_user_id"), "api_case_runs", ["trigger_user_id"], unique=False
    )
    op.create_table(
        "api_collection_run_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("collection_run_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("case_run_id", sa.String(length=64), nullable=True),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("continue_on_failure", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_run_id"], ["api_case_runs.run_id"], name="fk_api_collection_run_items_case_run"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_collection_run_items")),
        sa.UniqueConstraint("item_id", name=op.f("uq_api_collection_run_items_item_id")),
    )
    op.create_index(
        "idx_collection_run_item_order",
        "api_collection_run_items",
        ["collection_run_id", "order_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_collection_run_items_case_id"),
        "api_collection_run_items",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_collection_run_items_case_run_id"),
        "api_collection_run_items",
        ["case_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_collection_run_items_collection_run_id"),
        "api_collection_run_items",
        ["collection_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_collection_run_items_status"),
        "api_collection_run_items",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_collection_run_items")
    op.drop_table("api_case_runs")
    op.drop_table("api_cases")
    op.drop_table("ai_generate_run_imports")
    op.drop_table("ui_test_suites")
    op.drop_table("function_test_suites")
    op.drop_table("api_collections")
    op.drop_table("ai_generate_stage_attempts")
    op.drop_table("requirements")
    op.drop_table("ai_generate_run_stages")
    op.drop_table("worker_tasks")
    op.drop_table("users")
    op.drop_table("ui_test_suite_runs")
    op.drop_table("ui_test_suite_run_items")
    op.drop_table("ui_test_cases")
    op.drop_table("ui_test_case_runs")
    op.drop_table("sprints")
    op.drop_table("sprint_daily_metrics")
    op.drop_table("resource_bindings")
    op.drop_table("projects")
    op.drop_table("project_skill_spaces")
    op.drop_table("integration_connections")
    op.drop_table("function_test_cases")
    op.drop_table("api_extract_rules")
    op.drop_table("api_environments")
    op.drop_table("api_environment_vars")
    op.drop_table("api_collection_runs")
    op.drop_table("api_assert_rules")
    op.drop_table("ai_generate_tasks")
    op.drop_table("ai_generate_task_source_archives")
    op.drop_table("ai_generate_task_runs")
    # ### end Alembic commands ###
